server:
  tomcat:
    uri-encoding: UTF-8
  port: ${SERVER_PORT:8660}

spring:
  http:
    encoding:
      force: true
      charset: UTF-8
      enabled: true
  jackson:
    time-zone:  Asia/Shanghai
    date-format:  yyyy-MM-dd HH:mm:ss
  datasource:
    type: com.alibaba.druid.pool.DruidDataSource
    driver-class-name:  com.mysql.jdbc.Driver
  rabbitmq:
    host: ${RABBITMQ_HOST:192.168.1.122}
    port: ${RABBITMQ_PORT:5672}
    username: ${RABBITMQ_USERNAME:lc_domp}
    password: ${RABBITMQ_PASSWORD:lcservis2006}

##  mybatis配置
mybatis:
  mapper-locations: classpath:mapper/*.xml
  type-aliases-package: com.lcservis.lccloud.message.model


logging:
  level:
     root: info
     com.lcservis.lccloud.message : ${LOG_LEVEL:info}

# 分页配置
pagehelper:
  helper-dialect: mysql
  offsetAsPageNum:  true
  rowBoundsWithCount: true

ribbon:
  ReadTimeout:  60000
  ConnectTimeout: 60000
hystrix:
  command.default.execution.isolation.thread.timeoutInMilliseconds: 10000

#Netty 配置
netty:
  port: ${NETTY_PORT:8779}  # Netty 运行端口
  max-queue-size:  ${NETTY_MAX_QUEUE_SIZE:128}  # 最大队列数
  max-frame-length: 65535 #数据包最大长度